CREATE DATABASE GIUERA
USE GIUERA


CREATE TABLE USERS(
	id INT IDENTITY(1,1) PRIMARY KEY,
	firstName VARCHAR(64),
	lastName  VARCHAR(64),
	gender VARCHAR(8),
	email VARCHAR(128),
	address VARCHAR(128),
)


CREATE TABLE UserMobileNumber(
	phoneNum VARCHAR(64),
	userID FOREIGN KEY REFERENCES ADMIN(id),
	PRIMARY KEY(phoneNum,userID)
)

CREATE TABLE INSTRUCTOR(
	id INT FOREIGN KEY REFERENCES USERS(id),
	rating TINYINT
)


CREATE TABLE STUDENT(
	id INT FOREIGN KEY REFERENCES USERS(id),
	GPA DECIMAL(2,2))
)


CREATE TABLE ADMIN(
	id INT FOREIGN KEY REFERENCES USERS(id)
)

CREATE TABLE COURSE(
	id INT IDENTITY(1,1) PRIMARY KEY;
	creditHours INT,
	name VARCHAR(64),
	courseDescription VARCHAR(512),
	content VARCHAR(1024),
	adminID FOREIGN KEY REFERENCES ADMIN(id),
	instructorID FOREIGN KEY REFERENCES INSTRUCTOR(id),
)

CREATE TABLE ASSIGNMENT(
	cid INT FOREIGN KEY REFERENCES COURSE(id),
	number INT,
	type INT,
	fullGrade DECIMAL(2,2),
	weight INT,
	deadline DATE,
	content VARCHAR(1024),
	PRIMARY KEY(cid,number,type)
)

CREATE TABLE FEEDBACK(
	cid INT FOREIGN KEY REFERENCES COURSE(id),
	number INT,
	type INT,
	numLikes INT,
	comments VARCHAR(1024),
	sid INT FOREIGN KEY REFERENCES STUDENT(id),
       	PRIMARY KEY(cid,number,sid)
)

CREATE TABLE PROMOCODE(
	code varchar(16) PRIMARY KEY,
	issueDate DATE,
	expiryDate DATE,
	discountAmount DECIMAL(3,3),
	adminID FOREIGN KEY REFERENCES ADMIN(id)
)

CREATE TABLE studentHasPromoCode(
	sid INT FOREIGN KEY REFERENCES STUDENT(id),
	code INT FOREIGN KEY REFERENCES PROMOCODE(code),
	PRIMARY KEY(sid,code)
)


CREATE TABLE PROMOCODE(
	number VARCHAR(128) PRIMARY KEY,
	cardHolderName VARCHAR(128),
	expiryDate DATE,
	discountAmount DECIMAL(3,3),
	adminID FOREIGN KEY REFERENCES ADMIN(id)
)




